[package]
name = "libseat"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[dependencies]
errno = "0.2.7"
libseat-sys = {path="./libseat-sys"}

[[example]]
name = "simple"
